services:
  - type: web
    name: adguardhome
    runtime: docker
    dockerfilePath: ./Dockerfile
    portMappings:
      - port: 80
        targetPort: 80
      - port: 53
        targetPort: 53
        protocol: UDP
      - port: 53
        targetPort: 53
        protocol: TCP
      - port: 443
        targetPort: 443
        protocol: TCP
      - port: 443
        targetPort: 443
        protocol: UDP
