version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image for AdGuard Home
          command: docker build -t adguardhome .

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run basic tests
          command: |
            echo "Running tests..."
            # Testar se a imagem foi construída corretamente
            docker run --rm adguardhome --version

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy AdGuard Home container
          command: |
            docker run -d --name adguardhome \
              -p 53:53/tcp \
              -p 53:53/udp \
              -p 3000:3000 \
              adguardhome

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
