version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Download AdGuard Home binary
          command: |
            curl -L -S -o '/tmp/AdGuardHome_linux_amd64.tar.gz' 'https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz'
            tar -C /tmp/ -xzf /tmp/AdGuardHome_linux_amd64.tar.gz
            mkdir -p ./docker
            cp -r /tmp/AdGuardHome/* ./docker/

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image for AdGuard Home
          command: docker build -t adguardhome ./docker

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Test AdGuard Home container
          command: |
            echo "Running tests..."
            docker run --rm adguardhome --version

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy AdGuard Home container
          command: |
            docker run -d --name adguardhome \
              -p 53:53/tcp \
              -p 53:53/udp \
              -p 3000:3000 \
              adguardhome

workflows:
  version: 2
  setup-build-test-deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
